### ISSUE TITLE
the loop indexes

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GOCART#101]
https://github.com/GEOS-ESM/GOCART/blob/d79a878d8dbc08b771f5d4e07f034c84335fb966/ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridCompMod.F90#L1311-L1312

I think the indexes here should start from  i1 and j1  @tclune

**Comment by tclune** [comment]
It's not a bug though.  Just an anachronism.
