### ISSUE TITLE
GOCART2G does not layout regress

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GOCART#103]
As noticed in testing by @sdrabenh and myself, GOCART2G does not seem to currently layout regress. (It does start-stop regress, so that means we are not looking at a missing field in an internal state.)

When run at C48 with AMIP emissions, I see failures in both NI and SU restarts when I compare 4x24 to 4x30:
```
Comparing NC4 ni_internal_checkpoint using nccmp...
Failure!
Checking for data differences
Variable Group Count          Sum      AbsSum          Min         Max       Range         Mean      StdDev
NH3      /     11953  -2.8532e-30 2.28618e-29 -1.10441e-29 7.88861e-30 1.89327e-29 -2.38701e-34 1.25437e-31
NH4a     /      4754  4.16565e-30 8.98964e-29 -2.52435e-29 1.89327e-29 4.41762e-29  8.76241e-34 5.61762e-31
NO3an1   /      1847 -1.88273e-31  2.1484e-31 -1.97215e-31 6.16298e-33 2.03378e-31 -1.01934e-34 4.59288e-33
```

```
Comparing NC4 su_internal_checkpoint using nccmp...
Failure!
Checking for data differences
Variable Group Count          Sum      AbsSum          Min        Max       Range         Mean      StdDev
MSA      /     31294 -3.56464e-18 5.73955e-18 -1.73472e-18 2.1684e-19 1.95156e-18 -1.13908e-22 1.28398e-20
```

So not that big. But if we compare 4x24 to 2x48 *every single restart* is different:
```
$ cmpscratch scratch.4x24/ scratch.2x48/
Comparing NC4 achem_internal_checkpoint using nccmp...
Failure!

Comparing NC4 aiau_import_checkpoint using nccmp...
Failure!

Comparing NC4 cabc_internal_checkpoint using nccmp...
Failure!

Comparing NC4 cabr_internal_checkpoint using nccmp...
Failure!

Comparing NC4 caoc_internal_checkpoint using nccmp...
Failure!

Comparing NC4 catch_internal_checkpoint using nccmp...
Failure!

Comparing NC4 du_internal_checkpoint using nccmp...
Failure!

Comparing NC4 fvcore_internal_checkpoint using nccmp...
Failure!
...
```
Not good.

In the past, this sort of thing usually means there is a global sum, but I took a look and can't find any global reductions.

I talked with @bena-nasa and he had a possible thought: areas. AreaMean calls had caused issues in the past, but none of those. But, In `DistributePointEmission` in `GOCART2G_Process.F90` there is a calculation that involves the area:

https://github.com/GEOS-ESM/GOCART/blob/bb4eb2c42c3b0b290b6113dc4c628400e526ac6a/Process_Library/GOCART2G_Process.F90#L1086-L1087

@bena-nasa had some thoughts that maybe this area might not be guaranteed to always "conserve" under layout changes. (I'm not wording/explaining this correctly I'm sure; he or @tclune can explain better than I.)

So a question for @pcolarco, @adarmenov, @amdasilva, etc. who knows this code: Is there a way to disable or bypass the point emissions code? So we could do some tests to see if this code is bypassed, if layout regression is restored? (Comment out calls? Turn things off in ExtData?, etc...)

**Comment by tclune** [comment]
The code should not crash if we skip the point emissions.  Might need to set result to 0 or skip the addition.   I'll try to take a look at the point emission logic.

**Comment by pcolarco** [comment]
I *think* the volcanic emissions (set in SU2G_instance...) is using a separate code to the point emissions. But you can set the filename there to /dev/null

The only other entry point that might be used (but I think isn't in the FP config) is in the carbon components where there is an option to call point source emissions (e.g., pyroCb). You can also set the filename to /dev/null there.

Unless it's the volcanoes though I doubt this is the culprit.

**Comment by mathomp4** [comment]
@pcolarco Thanks. I tried setting `volcano_srcfilen:` to `/dev/null` in `SU2G_instance_SU.rc`. While it did change the answer, I still get all restarts different. So not that.

Hmm. I suppose I shouldn't solely blame GOCART. For example, we now use AChem right? That's a mystery box to me, though I only see area referenced in volcano stuff there as well and I don't think we use that code at the moment.

And are there other bits of GEOS that GOCART2G now uses that we used to avoid in GOCART1 days?

**Comment by mathomp4** [comment]
Tests I've tried so far:

- `/dev/null`'ing the SU volcano: regress fail
- Turning off achem: regress fail
- Turning off hemco: crash (can you tell I don't know what I'm doing 😄 )
- Blank history (just in case): regress fail

So, @pcolarco is there a way in GOCART2G to start turning off species/constituents/instances/not-sure-of-the-term? That way we could run with no SU, or no DU, etc. (I think there was a way in old GOCART, but I can't even remember how to do that.)

**Comment by sdrabenh** [comment]
@pcolarco setting AERO_PROVIDER:none and USE_AEROSOL_NN:0 still causes su_internal to fail for MSA field

**Comment by pcolarco** [comment]
@sdrabenh Have you tried not running SU and do you have this problem? 
And if I need to dig into this can you tell me what is being tried? I can just try changing the layout (NX,NY in my AGCM.rc)? And what is the preferred tool to verify the restarts are/are not identical?

**Comment by sdrabenh** [comment]
@pcolarco if I use defaults with no ACTIVE_INSTANCES_SU everything passes 0-diff regression. I imagine something is weird with SU. I am running the standard `./regress/gcm_regress.j` tool to check the decomposition. My tests are using `mepo clone -b feature/#328/geos-v10.17.6/gocart2g/new-extdata git@github.com:GEOS-ESM/GEOSgcm.git` build running at C48 with Reynolds data ocean (o1), new land (NLv3), and OPS emissions.

**Comment by pcolarco** [comment]
@sdrabenh Please send me a path to restarts used and I will try to play with it this morning.

**Comment by sdrabenh** [comment]
@pcolarco these are the restarts I use. All GOCART2G restarts are bootstrapped.
/discover/nobackup/projects/gmao/g6dev/sdrabenh/ZeroDiffTests/restarts-C48_CS_NL
