### ISSUE TITLE
GOCART2G_Process.F90 contains goto's, should be replaced with exit

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GOCART#106]
When looking at this file to try to find a regression problem I noticed multiple uses of the GOTO statement which should not be used in modern Fortran unless absolutely necessary. From my look at the code, these are not needed as this can be accomplished with the  proper modern Fortran way of doing this, which is the exit statement. The exit breaks you out of the do loop and takes you to the next executable statement after the enddo.
i.e. instead of 
```
   do i=1,n
    ! do some work
    if  (logical_condition) then
       goto 15
     endif 
     enddo
15 continue

! The following accomplishes the same thing and makes the code more readable
do i=1,n
  ! do some work
  if (logical_condition) exit
enddo
```

**Comment by tclune** [comment]
@bena-nasa  I cleared the assignees here.    Assignee for an issue is the person that will make the fix.   If you want no notify/ask individuals if the ticket should be acted upon, just use the "@" notation in the text.

**Comment by amdasilva** [comment]
Weiyuan, can you clean this up?
