### ISSUE TITLE
GOCART develop doesn't currently run with AMIP (at least)

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GOCART#129]
This might be something @amdasilva knows about, but just in case...

When I clone GEOSgcm `main` and then checkout the `develop` branch of GOCART, an AMIP run fails:

```
 Character Resource Parameter: DU_INTERNAL_RESTART_FILE:du_internal_rst
 Bootstrapping du_internal_rst
 Character Resource Parameter: SS_INTERNAL_RESTART_FILE:ss_internal_rst
 Bootstrapping ss_internal_rst
 Character Resource Parameter: CA.oc_INTERNAL_RESTART_FILE:caoc_internal_rst
 Bootstrapping caoc_internal_rst
pe=00091 FAIL at line=00461    CA2G_GridCompMod.F90                     <status=41>
pe=00091 FAIL at line=01799    MAPL_Generic.F90                         <status=41>
```

It seems to die on this line:
https://github.com/GEOS-ESM/GOCART/blob/9737da633cfc937969799be6cabe2cbd496aeb14/ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridCompMod.F90#L461

~Perhaps `HISTORY.rc` needs a change for GOCART `develop`? Not sure.~ Nope. Does not involve history.

**Comment by amdasilva** [comment]
Can you be more specific?  If this is HISTORY related, it has nothing to do with AMIP.

**Comment by mathomp4** [comment]
@amdasilva What I did was checkout `develop`, build, and then try to run an AMIP-emissions run for a day (the way I normally run things). And it crashed. I'm not sure why. I was just sort of idly speculating. 

But you are right, this does not involve History. I turned off all the collections, and the model still crashed at the same place.

**Comment by weiyuan-jiang** [comment]
The recent changes don't seem to involve those errors. Need further investigation...
