### ISSUE TITLE
Bug in getAerosolSum: Not sure of correct fix

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GOCART#136]
There appears to be a bug in `getAerosolSum` but I'm not sure of the right fix. As this routine is (eventually) used by GAAS, I'll assign to @amdasilva for now and see what he thinks the right fix as I can sort of think of two (and I'll cc @weiyuan-jiang).

The issue is that in this code:

https://github.com/GEOS-ESM/GOCART/blob/7a9dae64f6860248dd3a97bdfc41e8fb2887ef61/ESMF/GOCART2G_GridComp/GOCART2G_GridCompMod.F90#L2177-L2212

`aeroOut` is defined as `intent(out)` but it's never initialized to anything. So the first time it's used is:
```fortran
          aeroOut = aeroOut + ptr3d
```
and my guess is if this code was run with the right debugging flags, it would fail since `aeroOut` appears on the right side. 

I can think of two fixes:

1. Initialize `aeroOut` (to zero?)
2. Make `aeroOut` `intent(inout)`

I'm not sure of the right fix. (And they might be equivalent if my reading of `get_mixRatioSum` is correct.)

**Comment by adarmenov** [comment]
Agreed - aeroOut needs to be initialized to zero; summation is conditional on obtaining a valid/proper pointer. Good fix.

**Comment by tclune** [comment]
@weiyuan-jiang Please create a hotfix PR for this that does both:  zeros out aeroOut and moves the accumulation inside the conditional.

**Comment by weiyuan-jiang** [comment]
fixed and merged
