### ISSUE TITLE
Hard coded 3 hourly frequency in gocart2g

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GOCART#146]
@amdasilva @pcolarco @adarmenov  @weiyuan-jiang @tclune @mathomp4 

There is this issue reported in UFS that appears to involve gocart2g:
https://github.com/ufs-community/ufs-weather-model/issues/1190

now Matt noticed that a 4 hour vs 2 + 2 start/stop regression was failing. We then remembered there is a hard coded 3 hourly alarm in gocart2g! In these spots:
https://github.com/GEOS-ESM/GOCART/blob/v2.0.6/ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridCompMod.F90#L393
https://github.com/GEOS-ESM/GOCART/blob/v2.0.6/ESMF/GOCART2G_GridComp/SU2G_GridComp/SU2G_GridCompMod.F90#L480

If I change this to 2 hours, the 4 hour vs 2 + 2 regression passes. So it does seem possible this could be the problem for UFS. At the very least it seems like either whatever the point of this alarm is it either needs to be divisible by the job segment or perhaps we are not saving something in the internal state that needs to be checkpointed.

**Comment by pcolarco** [comment]
@bena-nasa I won't have the time this week to give a thoughtful look at this, sorry. But if we add H2O2 to the internal state in GOCART2G (this is I think the field which requires the alarm cycling) that will solve this problem?

**Comment by bena-nasa** [comment]
@pcolarco thanks for the fast response. I agree, based my quick look at the code, maybe adding h2o2 to the internal state could solve it. I'll just try adding that here real quick and see if it fixes the issue

**Comment by amdasilva** [comment]
There was a reason why the 3 hour alarm was hardwired, as not to give the user the illusion that they could specify any other value. An easier solution may involving changing the way we handle these oxidants.  They this oxidant recycling always apperead contrived in my opinion. So, stop trying to find a way to address this in code. There is no deep mandate to keep this algorithm. Let us discuss this in our aerosol group meeting.

**Comment by tclune** [comment]
At the bare minimum - if the 3 hour cannot be changed and it is not safe to checkpoint at other intervals, then invalid start/checkpoint times must be detected and provide a clear failure message.    Getting plausible but incorrect results is (almost) the worst possible failure.

**Comment by bena-nasa** [comment]
I tried for quite a while yesterday to fix this. I think there are two issues.
1. The alarm created needs the reference time to be set to a fix time each day not the model start time.
2. This 3 hourly field needs to be checkpointed.

Looking at the code I thought this would be trivial. Unfortunately we have another case of ESMF alarms not functioning properly. I tried setting the initial ringtime to 0z of that day (indeed if you look at the code some did set a new time to be z0 of the current day, then it is not used a few lines later when the alarm is created). In the 4 hour run the alarm ran at 21z but did not ring at 0z. In the 2+2 run the alarm ran at 21z, then again at 23z when the model was restarted. ESMF is well aware of the alarm issues and has been rewriting the alarm algorithms to a point where I can test them.

**Comment by bena-nasa** [comment]
@tclune @amdasilva @rmontuoro 
To summarize the issues:
1. This needs to be the ringtime that is set 0z of the current day rather than the current time of the clock: https://github.com/GEOS-ESM/GOCART/blob/v2.0.7/ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridCompMod.F90#L403
2. This internal variable that is updated by the import periodically needs to be checkpointed if there is any possibility of the model being run NOT at the alarm frequency:
https://github.com/GEOS-ESM/GOCART/blob/v2.0.7/ESMF/GOCART2G_GridComp/NI2G_GridComp/NI2G_GridCompMod.F90#L794
If you look self%xhno3 is passed to subroutines a little later where it is modified. So this needs to checkpointed in the ESMF internal state. To do this a internal new variable must be added to the statespec. Then at the end of the run method self%xhno3 should be copied to this the pointer that points to the internal state variable.

The issue however is that I tried exactly this and found that the ESMF_Alarm was not behaving properly as detailed in the previous comment.
My recommendation would be to implement a "simple alarm" for now we test the new ESMF_Alarm implementation and figure this. We could easily implement an alarm like class in the component internal state that rings at a periodic time.

**Comment by bena-nasa** [comment]
@amdasilva @pcolarco @tclune
Well, I'm flabbergastered. As originally reported here, there is a hard coded alarm in the nitrate component, that if you do not run your segments so they start and stop when the alarm is ringing, you can not get start/stop regression.

As I said, I thought there were 2 issues, 1 the alarm was just being created in a bad way, and needed to be relative to the same time each day, not whenever you started the model! And the self%xhno3 needed to be saved to the internal state. I had tried both of these but the issues with the esmf alarm not behaving right meant this was doomed.

Well, I don't know what to say. I've been testing a new ESFM alarm branch where they have completely rewritten the alarm implementation to fix the issues with it, and indeed, now the alarm is behaving properly. (An alarm set to ring at 0z and every n hours after that does actually do that). I then tested the regression with the new ESMF branch + fixes to what I thought were the issues with the code that I've detailed in several post in this issue

But, despite this, it still can not pass a 2 hour + 2 hour regression with a 3 hourly alarm in the code.

 I even tried, running say a 2 step run staring at 21z vs 2 1 step runs! This still fails, the strange thing is that all the restarts are zero diff except the NI restart. If you let regression run longer than the alarm frequency everything goes non-zero diff. 

Clearly there is something done at initialization or buried outside of the gridcomp in the process library that is not start/stop safe. 

Whatever it is is not obvious as I stare at the code.

**Comment by bena-nasa** [comment]
Ok, I figured out how to fix this, mystery solved. The bottom line is
1. The code in Sulfate and Nitrate will never pass a regression test unless the execution is exaction a multiple of the alarm segment. They are just coded wrong.
I've committed the proper way this these routines should have been coded on this branch:
https://github.com/GEOS-ESM/GOCART/tree/feature/bmauer/allow_arbitary_start_and_stop

2. Even with this fix, the ESMF alarms in the current esmf release just is not functioning properly. So either the alarm must be bypassed for now with some other alarm type mechanism until the updated ESMF alarm implementation is released hopefully in ESMF 8.4

**Comment by bena-nasa** [comment]
@amdasilva would you like me to update the branch I referenced above, merge develop, and invent a little bypass to the ESMF alarms so we can just fix this so that you can do start/stop regression for as long as this 3 hourly logic exists? We really need to be able to do start/stop regression tests at something less than 3 hours, that is just hinderance to debugging sometimes and I have he solution with just a little more work, as I said above?
