### ISSUE TITLE
the pointer association should be checked

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GOCART#149]
https://github.com/GEOS-ESM/GOCART/blob/27793f42421e82894d6668f20cd306fb9acb3f94/Process_Library/GOCART2G_Process.F90#L3338-L3614

It is not enough to check if (present(....)) . Some null-pointers are passed in so the association should be checked to avoid crashing when assigning values to them.

**Comment by weiyuan-jiang** [comment]
In the latest version, those arguments are not pointers any more. So I assume they have been allocated if they are present. Nothing is done so far. We will wait and see if NOAA's ufs is working with the latest version.

**Comment by amdasilva** [comment]
No action since May. Closing it for now.
