### ISSUE TITLE
GOCART develop crashing with out of bounds error after updates

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GOCART#156]
After the PR merged into develop today, when I tried using the gocart develop branch, it crashed with this out of bounds error when using the "debug" build:
```
forrtl: severe (408): fort: (3): Subscript #3 of the array DPFLI has value 0 which is less than the lower bound of 1
Image              PC                Routine            Line        Source
GEOSgcm.x          000000000F493DCF  Unknown               Unknown  Unknown
GEOSgcm.x          000000000146F764  gocart2g_process_        6302  GOCART2G_Process.F90
GEOSgcm.x          0000000001158F67  su2g_gridcompmod_        1078  SU2G_GridCompMod.F90
libesmf.so         00002AAAAB40A9E4  _ZN5ESMCI6FTable1     Unknown  Unknown
```
The odd thing is that if you examine the code, it seems like it should be protected from getting there
```
6299 if(LH .lt. 1) continue
6300
6301 do k = LH, km
6302 qls(k) = dpfli(i,j,k)/pdog(i,j,k)*rhoa(i,j,k)
6303 end do
```
I tried changing the continue to cycle, thinking that maybe it was that but same behaviour. Will continue investigating.

**Comment by tclune** [comment]
Next step is to either explicitly print the lbounds of the arrays involved or to run under the debugger to see the same.

Am guessing that `dpfli` might be an "edge" variable which starts at 0?  Not that this would explain things.  

Also - please edit your initial message above to include compiler + version.  Am suspecting a compiler bug.

**Comment by bena-nasa** [comment]
Hmm, maybe the cycle did do, I think I was rebuilding in the optimized build. Just rebuilt the debugged build and put the cycles in and it runs. So either it was the continue or we have a Heisenbug. I take a fresh look at this in the morning.

**Comment by tclune** [comment]
Hmm - I'd not even noticed that it said `continue` rather than `cycle`.     The former should have been a syntax error, so maybe you ran without a new executable until that was fixed?

**Comment by weiyuan-jiang** [comment]
@tclune @bena-nasa I amy introduce this bug. Let me take a took. It may be "exit" instead of cycle

**Comment by bena-nasa** [comment]
Yep, there were 4 continue statements that should have been cycle. Will make PR to fix

**Comment by weiyuan-jiang** [comment]
@bena-nasa @tclune I am sorry I messed up with  C++'s "continue". The four "continue" statement should be 'cycle'.

**Comment by tclune** [comment]
No problem.  It is just unfortunate that it is not a syntax error.  Usually such other-language constructs are caught by the compiler.

**Comment by mathomp4** [comment]
> No problem. It is just unfortunate that it is not a syntax error. Usually such other-language constructs are caught by the compiler.

Now that I understand the issue (I totally missed it yesterday looking at it with Ben because I guess I was in Python land...where `continue` is the right thing), it is annoying this isn't caught by the compiler. But, well, per the Standard:

> 1 Execution of a CONTINUE statement has no effect.

Since `CONTINUE` literally does nothing, I guess you can have them anywhere as long as it doesn't have a label at the front!
