### ISSUE TITLE
Documentation of RC files requested

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GOCART#163]
Our NOAA partners have requested more thorough documentation of the options presented in the various GOCART rc files.   They did not request any specific format, but presumably something that could be referenced by scientists without delving into source code.

@rmontuoro

**Comment by zhanglikate** [comment]
@tclune Also, about the imported Met. fields to GOCART, do you also have documentation that can help us to understand some details? For instance, the following 2 Met. variables in the " subroutine WetRemovalGOCART2G ", what are they exactly representing, total precipitation flux or only the precipitating flux?  Especially  in our  micro physics scheme which may be different to yours, better to understand it well, that can help us to connect the correct variables. Thanks very much.

   real, pointer, dimension(:,:,:), intent(in)  :: pfllsan ! 3D flux of liquid nonconvective precipitation [kg/(m^2 sec)]
   real, pointer, dimension(:,:,:), intent(in)  :: pfilsan ! 3D flux of ice nonconvective precipitation [kg/(m^2 sec)]

https://github.com/GEOS-ESM/GOCART/blob/821ef40859d6155c8594668e6261c97c49a935bc/Process_Library/GOCART2G_Process.F90#L2750-L2751

**Comment by tclune** [comment]
@pcolarco or @amdasilva  Can either of you answer this question?  Should be easy.

**Comment by pcolarco** [comment]
I don't really understand the distinction @zhanglikate is making. It is the 3d precipitation flux at grid level edges. The comment in the code seems as complete as what I see in GEOS_MoistGridComp.F90, where the field is defined. Hope this helps.

**Comment by zhanglikate** [comment]
@tclune @pcolarco Yes. We don't have the full of GEOS repo. Please let me know how to checkout it if we are allowed to do that. Thanks.

**Comment by pcolarco** [comment]
@tclune Can you help? Or do they have access to discover to just look at it?

**Comment by mathomp4** [comment]
You can see the Moist Gridded Component here: https://github.com/GEOS-ESM/GEOSgcm_GridComp/blob/develop/GEOSagcm_GridComp/GEOSphysics_GridComp/GEOSmoist_GridComp/GEOS_MoistGridComp.F90

**Comment by tclune** [comment]
@mathomp4 Thanks.
@pcolarco  Thanks - I had assumed that if it mattered then GOCART would be "aware" of the details.

**Comment by zhanglikate** [comment]
Thanks very much.

**Comment by tclune** [comment]
@dbarahon Can you look at the question above in this ticket about some moist quantities that are imported into GOCART.   NOAA may have follow up questions, so it will also be useful if you could agree to some telecon at some point.

**Comment by dbarahon** [comment]
Hi Tom,

I can’t see the rest of the ticket (only your email). But sure we can telecon  if there are questions about gocart and moist.

I am available until 3 today or between 11 and 3 next week.

Donifan

From: Tom Clune ***@***.***>
Reply-To: GEOS-ESM/GOCART ***@***.***>
Date: Friday, June 24, 2022 at 12:18 PM
To: GEOS-ESM/GOCART ***@***.***>
Cc: "Barahona, Donifan (GSFC-6101)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GOCART] Documentation of RC files requested (Issue #163)


@dbarahon<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbarahon&data=05%7C01%7Cdonifan.o.barahona%40nasa.gov%7Cd532b1a38b694869ecf508da55fd229a%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637916842935153313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oioEAiQwDRKTD7HwLOQev%2BMa5xswz8xeygCdls75%2BXc%3D&reserved=0> Can you look at the question above in this ticket about some moist quantities that are imported into GOCART. NOAA may have follow up questions, so it will also be useful if you could agree to some telecon at some point.

**Comment by dbarahon** [comment]
@wmputman may comment on GFDL MP, I am not sure about the details of the implementation.

**Comment by amdasilva** [comment]
This is kind of an unfocused issue entry.  Closing it for now as the conversations seem to have clarified the questions. As a matter of principle, rc files should be documented. On-line commends help, but we are yet to come up with an approach for documenting it more fully, in complete sentences. Having a ProTeX action dealing with rc files could work.
