### ISSUE TITLE
Add SetVm in ESMF/UFS/Aerosol_Cap.F90 for ESMF managed threading capability.

### ISSUE THREAD

**Issue by junwang-noaa** [GEOS-ESM/GOCART#165]
We are adding the ESMF managed threading in UFS weather model. Two lines of code need to be added to ESMF/UFS/Aerosol_Cap.F90.
```
diff --git a/ESMF/UFS/Aerosol_Cap.F90 b/ESMF/UFS/Aerosol_Cap.F90
index ad6dc04..d44ab1f 100644
--- a/ESMF/UFS/Aerosol_Cap.F90
+++ b/ESMF/UFS/Aerosol_Cap.F90
@@ -6,6 +6,7 @@ module Aerosol_Cap
   use NUOPC
   use NUOPC_Model, only : &
     NUOPC_ModelGet, &
+    SetVM,  &
     model_routine_SS            => SetServices,          &
     model_routine_Run           => routine_Run,          &
     model_label_Advance         => label_Advance,        &
@@ -75,6 +76,7 @@ module Aerosol_Cap
   private

   public :: SetServices
+  public :: SetVM

 contains
```

Could these two lines be added in the GOCART code? We expect no impact on the GOCART that does not use the ESMF managed threading. Thanks.

**Comment by junwang-noaa** [comment]
@tclune @weiyuan-jiang @theurich FYI.

**Comment by tclune** [comment]
@junwang-noaa I'm sure we can add those lines - but it may take some time before it appears in a release.

At first glance, it would appear that SetVM is not used, so I don't really see why these lines would matter.   Is it anticipation of further changes where SetVM is used?   In which case, maybe it is better to wait for those?

**Comment by junwang-noaa** [comment]
@tclune This is the exact question I had. Here is the answer from Gerhard: we do still need the public SetVM for GOCART. The reason is that it is through this mechanism the GOCART code  runs on exactly the same PETs as the threaded FV3 FCST component. This is important for the reference sharing between FCST and GOCART. It would not otherwise work under the ESMF-managed setup, where each component decides independently of how to use the PEs provided by the parent component.
However, the GOCART change is so minor, it should not affect what NASA is doing.

**Comment by theurich** [comment]
@tclune The SetVM is unsed under UFS. Notice that the GOCART cap change use associates SetVM with the generic version from NUOPC_Model, and makes it public. This is how the UFS driver can access it. This generic SetVM looks at [the defined NUOPC attributes](https://earthsystemmodeling.org/docs/nightly/develop/NUOPC_refdoc/node3.html#SECTION00037000000000000000), to handle the resource management for the component.

**Comment by tclune** [comment]
OK - so you are saying that the Aerosol_Cap is simply re-exporting a NUOPC entity so that some other layer (GOCART CAP) has access.  Wouldn't it make more sense to put the USE statement in GOCART CAP instead?      Seems odd to put it in a module that does not do anything with it.

**Comment by mathomp4** [comment]
@junwang-noaa Please see https://github.com/GEOS-ESM/GOCART/pull/166

**Comment by junwang-noaa** [comment]
@mathomp4 Great, thank you!
