### ISSUE TITLE
Unnecessary yaFyaml dependency in GOCART build system

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#184]
yaFyaml is not needed to build GOCART. However, the following dependency is included in the build system:
https://github.com/GEOS-ESM/GOCART/blob/e59ddd490f3bc413465317a89e5684cee68de8e8/CMakeLists.txt#L64

**Comment by mathomp4** [comment]
Ah. Nuts. Yeah. We probably need a "build like UFS" build test here as well.

@rmontuoro In MAPL we handle this via `USE_EXTDATA2G`. I'm guessing you are building MAPL with `-DUSE_EXTDATA2G=NO`?

**Comment by rmontuoro** [comment]
@mathomp4 - yes, we build MAPL with `-DUSE_EXTDATA2G=NO` in the UFS.

The yaFyaml dependency is required by MAPL though, not GOCART.

**Comment by mathomp4** [comment]
True. Indeed, there seem to be a lot of unneeded `find_package` in GOCART:

https://github.com/GEOS-ESM/GOCART/blob/4c941791d3d1fbea65dd5d2be330ada8c4951036/CMakeLists.txt#L61-L64

Those are needed by MAPL, not GOCART. @rmontuoro if I make up a hotfix patch, can you test it?

**Comment by rmontuoro** [comment]
@mathomp4 - sure. Thanks!

**Comment by mathomp4** [comment]
@rmontuoro Can you actually tell me exactly how you are building MAPL now? That is what CMake options? I should capture that.

**Comment by rmontuoro** [comment]
Here they are:
https://github.com/NOAA-EMC/hpc-stack/blob/74a20edac33e66b59aa82fed47c7b8189c14363c/libs/build_mapl.sh#L69-L78

**Comment by mathomp4** [comment]
@rmontuoro Okay can you try the `hotfix/mathomp4/184-ufs-cmake-fix`? (see #185)

**Comment by mathomp4** [comment]
@rmontuoro Actually, another question: what version of GOCART are you using? My draft PR is based on our `main` which is 2.1.0, but if you still use an older version, I'll need to hotfix that too.

**Comment by rmontuoro** [comment]
@mathomp4 - Thank you.
We are currently using rev. a342b1b215 in the [ufs-weather-model](https://github.com/ufs-community/ufs-weather-model)

**Comment by mathomp4** [comment]
> @mathomp4 - Thank you. We are currently using rev. [a342b1b](https://github.com/GEOS-ESM/GOCART/commit/a342b1b215c3d915948b1220843f9b30ea159401) in the [ufs-weather-model](https://github.com/ufs-community/ufs-weather-model)

Ah. Good then we can (for now) just hotfix 2.1.0 since you are (essentially) on that. I'm doing testing now and will coordinate with @amdasilva about getting a v2.1.1 out for you.

**Comment by rmontuoro** [comment]
@mathomp4 - `hotfix/mathomp4/184-ufs-cmake-fix` built successfully in the UFS after minor modifications listed in https://github.com/GEOS-ESM/GOCART/pull/185#issuecomment-1247314269
