### ISSUE TITLE
Are these threading setup necessary in SS2G_GridComp ?

### ISSUE THREAD

**Issue by weiyuan-jiang** [GEOS-ESM/GOCART#217]
https://github.com/GEOS-ESM/GOCART/blob/df0e5a80865e73a473f80bef1d198fa55f9baa40/ESMF/GOCART2G_GridComp/CA2G_GridComp/CA2G_GridCompMod.F90#L132-L133

Those corresponding lines and others are not found in SS2G_GridComp. @aoloso

**Comment by aoloso** [comment]
If SS doesn't have thread private data structures, then those lines won't be necessary.
