### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by mmanyin** [GEOS-ESM/GOCART#245]
The arrays  dqa  and  drydepositionfrequency   are allocated in the 'run' routines of CA, SS, DU and NI,  but never de-allocated. The fix should be zero-diff trivial.

**Comment by mathomp4** [comment]
@mmanyin I think this actually isn't a memory leak. Fortran will automatically deallocate allocatable arrays once you get out of scope. Things can get a bit tricky if they are derived data types (I know @tclune has mentioned this), but for this, all is good.

**Comment by tclune** [comment]
Just some minor clarification, to be safe.   _Local_ allocatable variables are deallocated when the code leaves the scope of the procedure.    This is not true for allocatable module variables, nor for local _pointer_ variables.

Of course, this is unfortunately somewhat a matter of faith in the compiler, as it is difficult to prove unless you have really good memory tools to monitor the situation.   But practice suggests that the major vendors generally get this right unless you do something "really cleaver"  (TM).

**Comment by mmanyin** [comment]
Very good, I stand corrected.  Thanks for clarifying-
