### ISSUE TITLE
Repository needs updated CODEOWNERS

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GOCART#26]
This repo at present does not have a `CODEOWNERS` file. I can add one, I just need to know who to put in it. I mean, I guess @gmao-esherman should be there in some way. 

I suppose it should reflect the [GEOSchem_GridComp CODEOWNERS](https://github.com/GEOS-ESM/GEOSchem_GridComp/blob/develop/.github/CODEOWNERS) file. But should I make a new "GOCART2G Team"?

ETA: Actually, there was a `CODEOWNERS` just not in `main` at the time. There is one in `develop` at least.

**Comment by gmao-esherman** [comment]
Yes, you can add me to the file.

**Comment by tclune** [comment]
Yes - and I think @adarmenov should also be added.   He can thank me later.  :-)
