### ISSUE TITLE
Volcanic SO2 emissions read incorrectly in UFS-GOCART

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#28]
Volcanic SO2 emissions are read incorrectly in UFS-GOCART. This might be related to inconsistent grid coordinate units when running MAPL with an external grid, and it is connected to MAPL closed issue [#680](https://github.com/GEOS-ESM/MAPL/issues/680) affecting point source emissions.

The picture below shows the `SO2EMVN` diagnostic variable as written by History:

<img width="720" alt="image" src="https://user-images.githubusercontent.com/18299064/109607163-71cc8a00-7aed-11eb-8bfd-639b9f1ea4cf.png">

**Comment by tclune** [comment]
Assigning to @bena-nasa

**Comment by WilliamJamieson** [comment]
@bena-nasa can you take a look at this?

**Comment by bena-nasa** [comment]
@WilliamJamieson was trying to teach me how to build and run the test. We had build issues, once those are sorted out a few prints should pinpoint the problem.

**Comment by bena-nasa** [comment]
I have found the problem. I've made a PR in MAPL to fix this https://github.com/GEOS-ESM/MAPL/pull/736
There was another bug in the implementation. I tested this in the UFS code and it seems to be assigning correctly here is an example:
```
91: bmaa pet:   91    14     6     72.59999997    -53.02999853     72.28835244    -53.33303965
 91: bmaa pet:   91    14     5     73.50999973    -53.11000053     73.68131709    -53.41511761
 85: bmaa pet:   85    13    16   -135.99999468    -76.05000365    223.62145897    -75.37749395
 85: bmaa pet:   85    11    22   -112.08000285    -76.27999661    249.60771019    -75.88858113
 89: bmaa pet:   89     9     1    -99.41999450    -74.32999810    261.82326841    -74.09423020
 89: bmaa pet:   89     4     4    -90.58000168    -68.85000072    269.47502307    -68.90359173
 89: bmaa pet:   89     3    20    -57.92999673    -62.09999797    302.07496821    -61.67727244
 89: bmaa pet:   89     3    18    -60.65000345    -62.97000015    298.89718942    -62.79584878
 89: bmaa pet:   89     5    19    -55.77000063    -63.58000434    303.43131329    -63.55781536
 95: bmaa pet:   95    18     1     51.75000059    -46.41999758     51.10834546    -46.43811190
 95: bmaa pet:   95    18     2     50.23000004    -46.09999980     50.05726243    -46.14204542
 95: bmaa pet:   95    12     9     37.94999952    -46.63000199     37.87571656    -46.97591323
 95: bmaa pet:   95    12     9     37.75000134    -46.90000278     37.87571656    -46.97591323
 94: bmaa pet:   94    10    12      3.34999989    -54.41999666      4.04189944    -54.49092890
 60: bmaa pet:   60    24    11   -156.25000293     20.70999929    203.81725110     20.89429938
  5: bmaa pet:    5    20    17    -14.36999914     -7.94999954    345.32991688     -7.74277128
```
The numbers are the processor, the assigned index i,j for that point, the values of the point that needs to be assigned to a grid cell if in the local domain, the value of the center lons/lats at that index. Looks good to me.

**Comment by rmontuoro** [comment]
Additional changes might be needed to solve this issue. See [comment](https://github.com/GEOS-ESM/MAPL/pull/736#issuecomment-790291896) in PR [#736](https://github.com/GEOS-ESM/MAPL/pull/736).

**Comment by bena-nasa** [comment]
This is now fixed in develop of MAPL
