### ISSUE TITLE
Input monochromatic wavelengths in nm for consistency 

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#29]
In the GOCART2G resource file, monochromatic wavelengths need to be provided in meters while other wavelengths are in `nm`:

```
# monochromatic wavelengths are in meters
aerosol_monochromatic_optics_wavelength: 4.7e-7 5.5e-7 6.7e-7 8.7e-7
wavelengths_for_profile_aop_in_nm: 470 550 870
wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
```

Using `nm` also for monochromatic wavelengths may improve consistency and prevent possible mistakes.

**Comment by tclune** [comment]
Assigned this issue to @adarmenov

**Comment by gmao-esherman** [comment]
Arlindo wanted the aerosol_monochromatic_optics_wavelength values in nanometers. This how they are written in my [branch](https://github.com/GEOS-ESM/GOCART/blob/feature/esherman/gocart2g_develop_MAPLconst/ESMF/GOCART2G_GridComp/GOCART2G_GridComp.rc). We convert these wavelengths to meters when we call Aero_Compute_Diags.

**Comment by gmao-esherman** [comment]
@tclune I don't know why the wavelengths are in meters the first comment. The wavelength values are in nanometers in my branch (please see the link in my previous comment).

I don't think it is up to me to decide if these changes go in.

**Comment by adarmenov** [comment]
Agreed, for the sake of consistency and readability the units in this case should be 'nm'.

**Comment by adarmenov** [comment]
@gmao-esherman what is the use of the 'monochromatic' wavelengths label/resource?

**Comment by gmao-esherman** [comment]
The _aerosol_monochromatic_optics_wavelength:_ are used by the aerosol components to create the diagnostic Mie tables, and used in the call to compute aerosol diagnostics.

These values used to be set in each aerosol's resource file (e.g. DU2G_GridComp_DU.rc). This implementation was a bit clumsy and makes it harder on the user. We now set this in GOCART2G_GridComp.rc and pass this information down to each child.

**Comment by rmontuoro** [comment]
> @amdasilva wanted the aerosol_monochromatic_optics_wavelength values in nanometers. This how they are written in my [branch](https://github.com/GEOS-ESM/GOCART/blob/feature/esherman/gocart2g_develop_MAPLconst/ESMF/GOCART2G_GridComp/GOCART2G_GridComp.rc). We convert these wavelengths to meters when we call Aero_Compute_Diags.

Thanks, @gmao-esherman - I see the changes in your PR #23. I'll close this issue once your PR has been merged.

**Comment by tclune** [comment]
Ok - good; glad we are on the same page then.    I did not mean to imply at all that this was your decision - just that you were much more likely to recall the details of that discussion with Arlindo than myself.

**Comment by amdasilva** [comment]
This has been implemented. Internally, however wavelengths remain in SI units (meters).
