### ISSUE TITLE
Remove print comments or convert them to pFlogger calls

### ISSUE THREAD

**Issue by WilliamJamieson** [GEOS-ESM/GOCART#32]
In reviewing the GOCART2G code, I have notice that there are many blocks of prints which appear to have been commented out. For example in the `NI2G_GridComp` there is the following block ([see 808 - 813](https://github.com/GEOS-ESM/GOCART/issues/28)):
```
!if(mapl_am_i_root()) print*,'NI2G Run2 BEGIN sum(NH3) = ',sum(NH3)
!if(mapl_am_i_root()) print*,'NI2G Run2 BEGIN sum(NH4a) = ',sum(NH4a)
!if(mapl_am_i_root()) print*,'NI2G Run2 BEGIN sum(hno3) = ',sum(nitrate_hno3)
!if(mapl_am_i_root()) print*,'NI2G Run2 BEGIN before sum(self%xhno3) = ',sum(self%xhno3)
!if(mapl_am_i_root()) print*,'NI2G sum(DU) = ',sum(DU)
!if(mapl_am_i_root()) print*,'NI2G sum(SS) = ',sum(SS)
```
There are many more examples scattered throughout all the other GOCART2G GridComps. 

It looks like these blocks are being toggled on and off via comments for debugging and diagnostic purposes. If this is the case then we should either remove them in the future or convert them into pFlogger calls (and provide a logging config that turns them on or off).

@tclue what do you think of this?

**Comment by mathomp4** [comment]
@tclune was misspelled. Adding to ping him...

**Comment by tclune** [comment]
Yes - these are debugging calls by @gmao-esherman, I'm fairly sure.         He should be the one to decide whether the need for these is now over (or nearly so) or if there is some long term value.  In the latter case, we should convert to pFlogger.  (But maybe not immediately, as impi has a bug that is likely to cause problems.)

**Comment by amdasilva** [comment]
@weiyuan-jiang please take a look. If these are commented prints, just remove them. If there are prints every herartbeat perhaps these need to removed or at least use the logger.

**Comment by weiyuan-jiang** [comment]
Almost all the prints have been removed by someone else. I think it is fine to keep those prints when status/=0.

**Comment by amdasilva** [comment]
OK, fair enough. This is addressed.
