### ISSUE TITLE
GOCART legacy causes error when building standalone GOCART

### ISSUE THREAD

**Issue by WilliamJamieson** [GEOS-ESM/GOCART#33]
GOCART's `develop` branch was capable of being built standalone prior to the reintroduction of GOCART legacy. This is a nice feature for CI testing. Due to this issue the CI testing was limited to just testing if the GOCART2G target builds, which ignores all of the UFS related code. Hence, GOCART-legacy should be updated, so that GOCART's `develop` branch can start building standalone.

I think the cause of the issue is related to a [comment](https://github.com/GEOS-ESM/GOCART/pull/24#discussion_r586105305) made by @rmontuoro noting that GOCART legacy's cmake should express an explicit dependency on MAPL. There are also some dependencies on Shared in GEOSchem_GridComp that need to be brought in as well. These dependencies were originally part of the GOCART repository, but where removed by earlier commits. I suggest bringing them back in until GOCART legacy is removed.

**Comment by amdasilva** [comment]
Obsolete. Legact GOCART has been retired.
