### ISSUE TITLE
Call to fill out Changelog!

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GOCART#46]
This is mainly a place for discussion, etc. from @rmontuoro and @gmao-esherman. Namely, I recently added the Changelog enforcer on GOCART since, well, if you have a Changelog, you should use it!

But, when I recently "created" a good-ish Changelog in `main`, I didn't really fill out much in the `Unreleased` section as I don't know GOCART well enough. But, comparing `develop` to `main` shows there are a lot of updates not yet in `main`:

https://github.com/GEOS-ESM/GOCART/compare/main...develop

I don't think this needs to be too detailed, but at least cover the major differences/fixes/etc. that distinguish GOCART `develop` from GOCART v1.0.1

So, if @rmontuoro and @gmao-esherman can maybe list things they think should be added from past commits here, I can work on making a Changelog update to `develop` so that we only have a single PR we need to get it up-to-date.

Thanks!

**Comment by gmao-esherman** [comment]
There were only structural changes with GOCART, right? GOCART from `develop` should zero-diff with GOCART v1.0.1. Maybe we can just say the changes were only structural.

**Comment by mathomp4** [comment]
> There were only structural changes with GOCART, right? GOCART from `develop` should zero-diff with GOCART v1.0.1. Maybe we can just say the changes were only structural.

Well, I guess I mean all the GOCART2G things you've done. And all the UFS-y stuff that Raffaele has done. GOCART1G is "static" really in `develop`. But 2G has changed!
