### ISSUE TITLE
Parallelize loops with OpenMP

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#48]
Loops could be parallelized using OpenMP to potentially increase GOCART runtime performance. This is crucial for operational applications.

OpenMP directive could be guarded in order to be more finely controlled and to prevent issues with existing applications, if necessary.

**Comment by amdasilva** [comment]
Tagging it as SomeDayMaybe. OpenMP parallelization perhaps should be done at a higher level.
