### ISSUE TITLE
Add NOAA/ARL FENGSHA dust scheme

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#49]
The FENGSHA dust scheme needs to be added as an optional scheme for the GOCART dust component.
This scheme, developed at NOAA/ARL, will be used in the UFS weather model.

**Comment by tclune** [comment]
@amdasilva has pointed out that some important updates to dust are in the process of being ported to 2G.    These changes will have some ramifications to this issue, and the merge will be need to be delayed until then.    I don't have a precise timeline, but we can ask for that at the telecon this Friday.
