### ISSUE TITLE
Reorganize GOCART process library into separate files

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#53]
It seems beneficial to reorganize the GOCART process library source code into separate units, as pointed out by @tclune. This will provide a code base easier to maintain.

One option would be to arrange the library into separate modules, each including only the procedures required by one GOCART component (_e.g._ DU, SS, etc.) .

**Comment by amdasilva** [comment]
Well, since several of the processes are shared by multiple species, separating the PL by specifies does not make too much sense. These perhaps shopuld be grouped by functionality.

**Comment by amdasilva** [comment]
Adding this to the SomeDayMaybe list. It is a good suggestion but difficult to prioritize at this point.
