### ISSUE TITLE
GOCART2G and MERRA2 Emissions: Update QFED?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GOCART#54]
I'm not sure if this is an @adarmenov or @pcolarco question...so I've tagged you both. 😄 

Namely, I tried running with MERRA2 Emissions today in the year of 2019 (trying to trigger a different issue) and, of course, things go boom:
```
pe=00084 FAIL at line=02163    MAPL_ExtDataGridCompMod.F90              <From ExtData/PIESA/sfc/QFED/v2.4r6/Y%y4/M%m2/qfed2.emis_bc.005.%y4%m2%d2.nc4 could not find time no extrapolation>
```
This is because QFED v2.4r6 doesn't exist in 2019. I used Ops emissions and got past this.

So I thought well, maybe this is fixed in GOCART2G, but:
https://github.com/GEOS-ESM/GOCART/blob/89cd8c7f970b0dda24dfccc6976761e17010d730/ESMF/GOCART2G_GridComp/CA2G_GridComp/MERRA2/CA2G_GridComp_ExtData.rc#L66

Still v2.4r6. 

My question is: should we take this opportunity of moving to GOCART2G (which is non-zero-diff by fiat) to also move to use, say, QFED v2.5r1? That actually does seem to exist in 2019 (and in 2021!). Or is v2.4r6 the only 'validated' version? (And I guess if so...how is MERRA2 running right now?)

**Comment by adarmenov** [comment]
@mathomp4  The name MERRA2 is a misnomer... The model version, setup, etc. has little to do with M2. 

To answer your question, FP and M2 are using QFED-2.5, so changing the QFED version from 2.4 to 2.5 would be fine. With that said, you are likely to hit other problems (e.g. the constituents file used in PCHEM) if you try to run the MERRA2 configuration of the box for a more recent date.

In case you are wondering why QFED-2.4 cannot be extended - it used MODIS Collection 5 fire products which were discontinued in 2017 or 2018 if I am not mistaken. This necessitated the development of QFED-2.5 which is based of MODIS Collection 6.x products.

**Comment by mathomp4** [comment]
@adarmenov Cool. Thanks. I leave updating these things to the scientists, I just get lazy and choose 'defaults' when I make experiments. I now realize I am lucky my "standard" test restarts are in Y2000; one year earlier and I would have been in a world of hurt when the default went from CMIP to MERRA2 :)

**Comment by pcolarco** [comment]
Matt-

I have no idea who all I’m replying to here…I’m not up to speed on git ticketing and how I should interact with it.

That said, I think I can make requested updates for you in some limited way. However there appear to be 8 different configurations of emission possible. I am checking with Arlindo but there is really no way to maintain and ensure these work for arbitrary user and I will recommend some more limited selection to propagate.

Pete


--------------------------------------------------------------------
Peter Colarco
NASA GSFC
Code 614
NASA Goddard Space Flight Center
Greenbelt, MD 20771
301.614.6382 (ph)
301.614.5903 (fax)

***@***.******@***.***>
http://acd-ext.gsfc.nasa.gov/People/Colarco
http://www.researcherid.com/rid/D-8637-2012
--------------------------------------------------------------------


From: Matthew Thompson ***@***.***>
Reply-To: GEOS-ESM/GOCART ***@***.***>
Date: Thursday, April 22, 2021 at 3:29 PM
To: GEOS-ESM/GOCART ***@***.***>
Cc: Peter Colarco ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [GEOS-ESM/GOCART] GOCART2G and MERRA2 Emissions: Update QFED? (#54)


@adarmenov<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fadarmenov&data=04%7C01%7Cpeter.r.colarco%40nasa.gov%7C45d00a1e4b974e1c39e908d905c4ca76%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637547165487647051%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Sy0%2F%2FETCCGnFfVJXdWB103ooKUbwNtd0MQngOnp81V4%3D&reserved=0> Cool. Thanks. I leave updating these things to the scientists, I just get lazy and choose 'defaults' when I make experiments. I now realize I am lucky my "standard" test restarts are in Y2000; one year earlier and I would have been in a world of hurt when the default went from CMIP to MERRA2 :)

**Comment by mathomp4** [comment]
I just now encountered an issue with this. I was trying to run GOCART2G with MERRA2 emissions and now it turns out you can't run that in the year 2000! Why? Well something in GOCART2G is using the v2.5 NRT QFED. So...yeah. I guess you either use NRT exclusively and have a lower-end limit of emissions or not use NRT and cap the year you can run in? (CC @gmao-esherman )

**Comment by pcolarco** [comment]
@mathomp4 I get this message. This needs a larger conversation in the aerosol group. @amdasilva needs to be part of this.

**Comment by amdasilva** [comment]
This issue will be better handled with the planned upgrade of ExtData where time ranges will be allowed in the rc files: for time in this range use this set of emissions, for time in that time range use that set of emissions. 

In any event, use of NRT emissions should be discouraged. Only applications with a low-latency requirement (such as FP and IT) should use the NRT stream. Any other run, including reanalyzes, should use the non-NRT version of the emissions. TRhe same goes for AOD data.
