### ISSUE TITLE
Add OH_GridComp

### ISSUE THREAD

**Issue by mmanyin** [GEOS-ESM/GOCART#57]
An OH_GridComp exists in Icarus-vintage code.  It is a key part of the ECCOH functionality (coupled CO/CH4/OH).  As such, it should be integrated into the legacy GOCART routines.

**Comment by amdasilva** [comment]
Issue to be revised with the refactoring of the carbon components a la GOCART-2G. The Legacy GOCART is currently frozen to any further development.

**Comment by mmanyin** [comment]
OH will actually be a member of the QuickChem module currently under development. @amdasilva thanks for closing this.
