### ISSUE TITLE
Incorrect Aerosol Optical Depth

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#64]
Wavelength-dependent Aerosol Optical Depths (AODs) are computed incorrectly due to `aerosol_monochromatic_optics_wavelength` being read as a list of integers as opposed to reals by the GOCART2G gridded component.

This array of wavelengths (channels) are provided in units of `m` and therefore read as `0`s:

```
aerosol_monochromatic_optics_wavelength: 4.7e-7 5.5e-7 6.7e-9 8.7e-7
```
These wavelengths are further multiplied by `1.e-09` internally before computing AODs using the diagnostic Mie lookup table.

I suggest entering the `aerosol_monochromatic_optics_wavelength` in units of `nm` for consistency with other settings and updating the internal code appropriately. The configuration label may also be updated as `aerosol_monochromatic_optics_wavelength_in_nm` to reflect this change and to improve consistency. For example:
```
wavelengths_for_profile_aop_in_nm: 470 550 670 870
wavelengths_for_vertically_integrated_aop_in_nm: 470 550 670 870
aerosol_monochromatic_optics_wavelength_in_nm: 470 550 670 870
```

**Comment by tclune** [comment]
@rmontuoro  Agreed.   I know @amdasilva had strong opinions on whether things were in nm or m.   I thought he preferred nm, so I'm a bit surprised the other form survived review.

Do you have a PR, or should I assign this to @weiyuan-jiang ?

**Comment by rmontuoro** [comment]
@tclune - PR #65 addresses this issue. Please let me know your preference regarding renaming the config label.

**Comment by amdasilva** [comment]
rc files specify wavelengths in nm, internally calculations use m. This issue has been dealt with.
