### ISSUE TITLE
Add wet removal efficiency parameters to config files for external tuning

### ISSUE THREAD

**Issue by rmontuoro** [GEOS-ESM/GOCART#69]
It would be helpful to include _wet removal efficiency_ (`fwet`) as a tuning parameter in each of the GOCART2G subcomponents for increased flexibility.

**Comment by tclune** [comment]
@amdasilva  - Can you comment on this question from @rmontuoro ?

**Comment by amdasilva** [comment]
Good suggestion. Wet removal is expected to be moved to its own component. When doing so I will make sure that parameters are rc file driven.
