### ISSUE TITLE
Clean up nm to m conversion in GOCART2G

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GOCART#73]
`wavelengths_diagmie` is still declared as `integer`: https://github.com/GEOS-ESM/GOCART/blob/58af7747eba91dc597c65485a5e4e781cb25deca/ESMF/GOCART2G_GridComp/GOCART2G_GridCompMod.F90#L113
which is inconsistent with `self%wavelengths_profile` and `self%wavelengths_vertint` (`real`).

I would still recommend including changes from PR #65 into this branch to address this issue and streamline the code. For example, conversion from `nm` to `m` should be done only once (see https://github.com/GEOS-ESM/GOCART/pull/65/files#diff-682724d291af0ad213c4e1b2ffa97156de4989543290b60bf362adfa98e3d8da):

https://github.com/GEOS-ESM/GOCART/blob/b9fa4c6c0ed46e43dae1a66aaa296a0d72ff839f/ESMF/GOCART2G_GridComp/GOCART2G_GridCompMod.F90#L156-L162

_Originally posted by @rmontuoro in https://github.com/GEOS-ESM/GOCART/pull/68#discussion_r684312869_

**Comment by amdasilva** [comment]
This is less of an issue now since these calculations are now done at array level with the refactoring of the Mie calculations.
