### ISSUE TITLE
Add new Resource File Instance for GEOS-IT

### ISSUE THREAD

**Issue by amdasilva** [GEOS-ESM/GOCART#87]
# What is it?

The new GEOS-IT that is starting in late 2021 is based on GOCART tag v1.0.1 which only contains the old Legacy GOCART implementation. To improve the simulation of anthopogenic aerosols we will use the CEDS emissions.

# New Feature
This new resource file instance should use the CEDS anthropogenic emissions and the MODAPS based (non-NRT, LANCE) version of QFED.  Dust and Seasalt will not be modified.

**Comment by rtodling** [comment]
In Chem this can not incorporate the change in Henry's Law for ammonia - agreement reached at NWP group. This is motivated by the fact that 5.29 will be used for FP and more importantly for the long-run of GEOS-IT.

**Comment by rtodling** [comment]
unfortunately the changes for emissions are causing the model to crash:

pe=00287 FAIL at line=02059    MAPL_ExtDataGridCompMod.F90              <Clim year must be month template "%m2">
pe=00287 FAIL at line=01042    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00287 FAIL at line=01840    MAPL_Generic.F90                         <needs informative message>

I have tested that use of the standard OPS emissions work just fine. So something is amiss in the new files or the dir structure or something ... don't know yet want the problem.

**Comment by rtodling** [comment]
I think I found the problem ... testing ...

**Comment by bena-nasa** [comment]
@rtodling @amdasilva 
Can you point me to the updated ExtData rc files? Sounds like you are trying to do something that is not supported, a look at the rc files should hopefully let me see what the problem is.

**Comment by rtodling** [comment]
I placed two ExtData.rc files under:

/discover/nobackup/rtodling/4AMS/

one subdirectory is OPS (that works); another is GEOSIT (the new one that does not work).

I've been doing some check to see if I find missing files somewhere; so far I have not ... I wonder if one of the files is corrupt. I am running on 20190625.

I can already detect other issues: some of the data only goes as far back as 1999 - GEOSIT starts (in spin-up mode) in 1997. 
E.g.:
chemistry/CEDS/v2021-04-21/sfc/NH3-em-anthro_CMIP_CEDS_gn.x2304_y1441_t12.1999.nc4  
is the earliest of its type (there are other types in this collection of CEDS that suffer from the same issue)
another case is here:
MERRA2GMI/v0.0.0/L72/MERRA2_GMI.tavg24_3d_dac_Nv.x576_y361_t12.%y4.nc4

**Comment by rtodling** [comment]
I am just noticing that we have (in both old and new) tons of wired files to Anton's home dir:

/home/adarmeno/projects/SOAG/

what is this?

**Comment by bena-nasa** [comment]
@rtodling 

What is the actual directory that gets linked under ExtData for the GEOSIT run so I can look at the files? As far as the rest of the gocart setup, is this just OPS with new ExtData.rc and linking in a different chemistry directory

As for the files in people personal spaces, that's between the ops group and the maintains of those particular file sets/individual ExtData rc files to get those datasets to the ops space rather than individual user spaces.

**Comment by rtodling** [comment]
chemistry

**Comment by rtodling** [comment]
That's a new directory now.

I deleted my comments of personal dir stuff - I realized this is all stuff that is under development not used by anyone else. No need to worry about it

**Comment by bena-nasa** [comment]
> chemistry

No, what is the absolute path that gets linked under ExtData in the scripting, I can't find the files without that.

**Comment by rtodling** [comment]
It's tough to figure out which entry is doing this. That's what I am trying to do ... can do a cross-validation test replace parts of the new w/ the working parts of the old ...

**Comment by amdasilva** [comment]
Just committed update with fix templates for the CEDS emissions in @GOCART.

For GEOSchem_GridComp, ignore my branch and go back to rt1.6.2
