### ISSUE TITLE
Possible bug in GOCART2G or just a naming issue: bext or tau?

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GOCART#88]
There might be a bug in GOCART2G, though maybe it's just "bad variable name" instead of bug. The code is a bit confusing to me at times. 😄 

To wit, I was looking at trying to improve the performance of GOCART2G (as @wmputman has said he sees it slower). I was trying to convert some MieQuery calls from "in a 4-d loop" to "in a band loop" when I saw this (showing DU, but it's in all):

https://github.com/GEOS-ESM/GOCART/blob/8cee2066223f686bd96989a6253ee864e498b7a5/ESMF/GOCART2G_GridComp/DU2G_GridComp/DU2G_GridCompMod.F90#L1196-L1202

The issue is that a keyword is *not* being used for `bext`. If we now look at the signature of `Chem_MieQuery` → `Chem_MieQueryInt`:
```fortran
   impure elemental subroutine Chem_MieQueryByInt ( this, idx, channel, q_mass, rh,     &
                                   tau, ssa, gasym, bext, bsca, bbck,  &
                                   reff, p11, p22, gf, rhop, rhod, &
                                   vol, area, refr, refi, rc )


! !INPUT PARAMETERS:


   type(Chem_Mie), target, intent(in ) :: this
   integer,                intent(in ) :: idx     ! variable index on Chem_Mie
   real,                   intent(in ) :: channel ! channel number 
   real,                   intent(in ) :: q_mass  ! aerosol mass [kg/m2],
   real,                   intent(in ) :: rh      ! relative himidity


! !OUTPUT PARAMETERS:


   real,    optional,      intent(out) :: tau   ! aerol extinction optical depth
   real,    optional,      intent(out) :: ssa   ! single scattering albedo
   real,    optional,      intent(out) :: gasym ! asymmetry parameter
   real,    optional,      intent(out) :: bext  ! mass extinction efficiency [m2 (kg dry mass)-1]
   real,    optional,      intent(out) :: bsca  ! mass scattering efficiency [m2 (kg dry mass)-1]
   real,    optional,      intent(out) :: bbck  ! mass backscatter efficiency [m2 (kg dry mass)-1]
...
```
we can see that the first optional argument is `tau`, not `bext`. I believe per Fortran this means we are actually doing:
```fortran
        call Chem_MieQuery(mie_table, l, real(offset+1.), q(:,:,:,l), rh, tau=bext, gasym=gasym, ssa=bssa)
```
We are filling `bext` with `tau` *not* `bext`. @tclune can confirm if I'm correct.

Now `bext` does seem related to `tau`:
```fortran
      if(present(tau  )) tau   = bextIn * q_mass
      if(present(bext )) bext  = bextIn
```
by `q_mass`. 

So my question for @amdasilva or @pcolarco is: do you want `tau` here or `bext`? If `tau`, then it's not a bug, just a bad name and all is well. But if this is supposed to be `bext` it might be incorrect code.

**Comment by mathomp4** [comment]
Talking with @aoloso on this, we think this is just a case of "bad name" not bug. I just wanted to be sure.

**Comment by pcolarco** [comment]
@mathomp4 This is not a bug (i.e., does not lead to erroneous/unexpected result) but is confusing in how it was implemented. The distinction of "bext" from "tau" is not intuitive and should be cleaned up more thoroughly in the code, but for now I added the appropriate keyword and verified zero-diff in the result. I will work with @mmanyin to check this in.

**Comment by mathomp4** [comment]
@pcolarco Okay. Just a "confused non-scientist" thing then. I figured you all would have noticed something being off by Q! 😄
