### ISSUE TITLE
Inefficient loop

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GOCART#92]
From @amdasilva
>The Mie interface is extremely inefficient and has slowed down radiation a great deal as noted by Bill. Making subroutine calls inside a deep do-loop is a big part of it.

 
```f90
   do n = 1, nbins
      do i = 1, i2
        do j = 1, j2
          do k = 1, km
            call Chem_MieQuery(self%diag_MieTable(instance), n, mieTable_index, q_4d(i,j,k,n), rh(i,j,k), tau(i,j,k), __RC__)
            tau_s(i,j,k) = tau_s(i,j,k) + tau(i,j,k)
          end do
        end do
      end do
    end do
```
@tclune thinks that the array interface has already been overloaded for this.

**Comment by mathomp4** [comment]
@weiyuan-jiang @tclune I'm actually thinking this might be expensive:

https://github.com/GEOS-ESM/GOCART/blob/8cee2066223f686bd96989a6253ee864e498b7a5/Process_Library/GOCART2G_Process.F90#L3513-L3544

There is another one below that. I saw these when looking at the GNU+GOCART2G issue with @aoloso 

These are 5-deep do-loops calling Chem_MieQuery. That is...not cheap is my guess.

**Comment by tclune** [comment]
With a bit of trouble, ELEMENTAL can be made to work.   @amdasilva has indicated he prefers a vanilla overload.   I'm pushing back because it is a substantial amount of duplicated code.      I suspect we'll need to do both and then time them.  If ELEMENTAL is as fast as the overload (which it should be), I'll defer to @amdasilva whether the little wrapper involved is too ugly for that approach.

**Comment by tclune** [comment]
Now that @weiyuan-jiang has reworked Mie, this loop should be simplified to use the multi-dimensional interface.

**Comment by amdasilva** [comment]
Refactoring of the Mie calculations has taken care of this.
