### ISSUE TITLE
Correct handling of state vars in multiple instances of component

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GOCART#93]
From @amdasilva 
>The other issue is the variable names in the multiple-instances of a component, CA, in particular.
```
CAMASS*    | kg kg-1    | xyz | C   |       | Carbonaceous Aerosol Mass Mixing Ratio                
CACONC*    | kg m-3     | xyz | C   |       | Carbonaceous Aerosol Mass Concentration               
CAEXTCOEF* | m-1        | xyz | C   | size(self%wavelengths_profile) | Carbonaceous Aerosol Extinction Coefficient 
CASCACOEF* | m-1        | xyz | C   | size(self%wavelengths_profile) | Carbonaceous Aerosol Scattering Coefficient
```
 
>In the case that the instance is called CA.oc, the first variable becomes CAMASSOC, while it should have been OCMASS for backward compatibility. Then long name is now the same for OC, BC and BR.  Should not have been done this way, but instead

``` 
*MASS    | kg kg-1    | xyz | C   |       | * Carbonaceous Aerosol Mass Mixing Ratio                
*CONC    | kg m-3     | xyz | C   |       | * Carbonaceous Aerosol Mass Concentration               
*EXTCOEF | m-1        | xyz | C   | size(self%wavelengths_profile) | * Carbonaceous Aerosol Extinction Coefficient 
*SCACOEF | m-1        | xyz | C   | size(self%wavelengths_profile) | * Carbonaceous Aerosol Scattering Coefficient
```

>Where * gets replaced by OC, BC, BR. Also he has code like this that is not used for anything. 

```f90
    if (comp_name(1:5) == 'CA.oc') then
       GCsuffix = 'OC'
    else if (comp_name(1:5) == 'CA.bc') then
       GCsuffix = 'BC'
    else if (comp_name(1:5) == 'CA.br') then
       GCsuffix = 'BR'
    end if
```

>As it turns out, the variables are unnecessarily different.  Also, no provisions for multiple instances in the other components.

@tclune will make any needed corrections to the MAPL ACG for this.    This ticket is solely about correcting the usage in GOCART gridcomps when those fixes are available.

**Comment by weiyuan-jiang** [comment]
Where is the original issue ?

**Comment by amdasilva** [comment]
@tclune Have the updates above been implemented in ACG?

**Comment by tclune** [comment]
Yes - but we failed to merge that PR into MAPL develop until last night.   I'd forgotten that I was waiting to confirm that it worked in GOCART and then lost track.   So it is now on the develop branch and @mathomp4 will be rolling out a MAPL minor release this morning.

**Comment by amdasilva** [comment]
@weiyuan-jiang Changes need to be made in GOCART2G state specs and all HISTORY in gcm app needs to adjusted to reflect the new variable mames. This will create a PR in gcm app.

**Comment by amdasilva** [comment]
This seems to have been done.
