### ISSUE TITLE
Refactor  Chem_MieTableMod2G.F90

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/GOCART#96]
No longer needed as we do not aggregate across tracers.

**Comment by tclune** [comment]
There is a laundry list of changes needed:

- The module name should change
   -  "2G" should be before "Mod"
   - "Table" should go away
   - Filename should be updated accordingly  (`git mv`)
-  Chem_Mie type goes away
-  Chem_MieTable is renamed to Chem_Mie
-  Use modern Fortran
    - POINTER components should be ALLOCATABLE
    - Chem_MieQuery should be a type-bound procedure
    - Constructor should be the same name as the type (requires interface block)
- "nlambda" component should be "nch" and documented as number of _channels_
- Create and Read methods should be fused into a single constructor
- QueryByInt should be QueryByScalar
- WithPmom should be QueryByVector
- New interface should allow passing frequency instead of channel
   - need new helper procedure that computes channel (int) from frequency (float)
   - just use placeholder for now
   -

**Comment by weiyuan-jiang** [comment]
In the elemental procedure, I suspect it creates 3d channels and idx which are not necessary when 3d is called

**Comment by weiyuan-jiang** [comment]
> * WithPmom should be QueryByVector
Comparing Withpmom with byInt, there is one more 2d optional argument pmom(:,:) in Withpmom. I saw the comment that this subroutine may be deleted.

**Comment by weiyuan-jiang** [comment]
> * "nlambda" component should be "nch" and documented as number of _channels_

Should we change lambda(:) to channels(:) in the component too?

**Comment by tclune** [comment]
ELEMENTAL only "creates arrays" for the arguments that _are_ arrays.  The "THIS" object remains a scalar, as does idx.  Maybe others - have not looked.


> * WithPmom should be QueryByVector
>   Comparing Withpmom with byInt, there is one more 2d optional argument pmom(:,:) in Withpmom. I saw the comment that this subroutine may be deleted.

No - pmom is a different shape and thus prevents ELEMENTAL.  I pulled it into a separate interface precisely because of that.

**Comment by amdasilva** [comment]
It has been done with PR on 3/17/2022.
